name: Bug report
description: Report a bug
labels: ["bug"]

body:
  - type: dropdown
    id: bugtype
    attributes:
      label: Is it a map, schematic, or mod?
      options:
        - Map
        - Schematic
        - Mod
        required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Explain your issue in detail.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How you came across the issue, and what exactly you did to make the bug happen.
    validations:
      required: true
 
  - type: checkboxes
    id: agreement
    attributes:
      label: Submission
      description: Check the boxes to confirm that you have read the lines below.
      options:
        - label: I have checked the Trello and made sure this has not already been fixed.
          required: true
        - label: I have searched the closed and open issues to make sure that this problem has not already been reported.
          required: true
