blank_issues_enabled: false
contact_links:
  - name: Submit idea
    url: https://trello.com/invite/b/KwcIRczQ/ATTI1ed7a8a74da118a24cbe1875755402176C1DBAB2/schematic-map-maker
    about: Submit a schematic, map, or mod idea.
  - name: Question
    url: <a href="mailto:callmesirentertainment@outlook.com">callmesirentertainment@outlook.com</a>
    about: Questions can be sent to me directly.
